"""Vendor the arena's typefaces, latin subsets only.

    python scripts/fetch_fonts.py

Vendored for the same reason Vue is: a demo that needs the internet is a demo
that fails in the room. The arena gets projected in a hall on whatever network
happens to exist, and a typeface that falls back mid-presentation is a page
that looks broken at the worst possible moment.

Only the subsets actually used are kept — latin for the interface, devanagari
for प्रमाण in the masthead. The full families are ten times the size and every
byte of the rest is Cyrillic and Vietnamese nobody will render.

IBM Plex is SIL OFL 1.1.
"""

from __future__ import annotations

import re
import urllib.request
from pathlib import Path

CSS_API = "https://fonts.googleapis.com/css2"
UA = {
    # Google serves woff2 only to browsers it recognises; the default urllib
    # agent gets truetype, which is three times the size.
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
        "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36"
    )
}

STATIC = Path(__file__).resolve().parents[1] / "praman" / "api" / "static"
FONT_DIR = STATIC / "vendor" / "fonts"

FAMILIES = (
    ("IBM+Plex+Sans:wght@400;500;600;700", "latin", "plex-sans"),
    ("IBM+Plex+Mono:wght@400;500;600", "latin", "plex-mono"),
    ("IBM+Plex+Sans+Devanagari:wght@600", "devanagari", "plex-deva"),
)

HEADER = """/* Vendored typefaces — generated by scripts/fetch_fonts.py, do not edit.
 *
 * Latin subsets for the interface, devanagari for प्रमाण in the masthead.
 * Vendored rather than linked so the arena renders identically with no
 * network, which is the same reason Vue is vendored.
 *
 * IBM Plex, SIL OFL 1.1.
 */

"""


def fetch(url: str) -> bytes:
    return urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=30).read()


def main() -> int:
    FONT_DIR.mkdir(parents=True, exist_ok=True)
    faces: list[str] = []

    for spec, subset, slug in FAMILIES:
        css = fetch(f"{CSS_API}?family={spec}&display=swap").decode()
        # Each @font-face is preceded by a comment naming its subset. That
        # comment is the only thing distinguishing eight otherwise identical
        # blocks, so the parse keys off it rather than off the unicode-range.
        for comment, face in re.findall(r"/\* (\S+) \*/\s*(@font-face \{.*?\})", css, re.S):
            if comment != subset:
                continue
            weight = re.search(r"font-weight: (\d+)", face).group(1)
            source = re.search(r"url\((\S+?)\)", face).group(1)
            name = f"{slug}-{weight}.woff2"
            (FONT_DIR / name).write_bytes(fetch(source))
            faces.append(face.replace(source, f"fonts/{name}"))
            print(f"  {name:<22} {(FONT_DIR / name).stat().st_size / 1024:>6.1f} KB")

    stylesheet = STATIC / "vendor" / "fonts.css"
    stylesheet.write_text(HEADER + "\n".join(faces) + "\n", encoding="utf-8")
    print(f"\n  wrote {len(faces)} faces to {stylesheet.relative_to(STATIC.parents[2])}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
